# Generated by Django 4.2.16 on 2025-10-27 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopApp', '0002_alter_productpackage_size'),
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('در حال انتظار', 'pending'), ('تأیید شده', 'confirmed'), ('ارسال شده', 'shipped'), ('تحویل داده شده', 'delivered'), ('لغو شده', 'canceled')], default='در حال انتظار', max_length=20)),
                ('cart_number', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('wallet', 'کیف پول'), ('cod', 'پرداخت در محل')], max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('پرداخت شده', 'پرداخت شده'), ('در انتظار پرداخت', 'در انتظار پرداخت'), ('در انتظار تایید', 'در انتظار تایید'), ('ناموفق', 'ناموفق'), ('لغو شده', 'لغو شده')], default='در انتظار پرداخت', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('در حال انتظار', 'pending'), ('تأیید شده', 'confirmed'), ('ارسال شده', 'shipped'), ('تحویل داده شده', 'delivered'), ('لغو شده', 'canceled')], default='در حال انتظار', max_length=20)),
                ('shipping_method', models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('express', 'پیک موتوری')], default='post', max_length=20)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField()),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('jalali_delivery_date', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.clientaddress')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.productpackage')),
            ],
        ),
    ]
