# Generated by Django 4.2.16 on 2026-04-26 15:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import shop.utils.image_uploders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم  --  فارسی --  دسته بندی اصلی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='اسم- --انگلیسی-- دسته بندی اصلی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_BaseCategory_image_path, verbose_name='عکس دسته بندی اصلی')),
                ('brands', models.ManyToManyField(blank=True, related_name='base_categories', to='public.brand', verbose_name='برند های دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی  اصلی ',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---انگلیسی')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_cat_image_path, verbose_name='عکس دسته بندی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('base_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.basecategorys', verbose_name='دسته بندی اصلی')),
                ('brand', models.ManyToManyField(blank=True, related_name='categories', to='public.brand')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
    ]
